package com.bateai.entity.enums;

public enum StatusVinculo {
    PENDENTE_COLABORADOR,
    APROVADO_COLABORADOR,
    REJEITADO_COLABORADOR,
    DESLIGADO_COLABORADOR,

    PENDENTE_COORDENADOR,
    APROVADO_COORDENADOR,
    REJEITADO_COORDENADOR,
    DESLIGADO_COORDENADOR
}